feat: add dashboard & eslint linter (#159)
* fix(channel): fix error `ReferenceError: channelIdFromMention is not defined`

* build(reinstall): reinstall discord-player

* fix(music): trying to debug

* style: 🎨 format code

* fix(dash): fix sidebar

* docs: readme, add open in vscode badge

* fix(beg): increase winning chance

* fix(syntax): json syntax error

* docs: commands

* fix(dash): :bug: minor fixes

* fix(nav link): show on phones too

* fix(dash): minor fixes in profile

* fix(dash)

* feat(dash): :sparkles: add dashboard main page

* style: 🎨 format code

* fix(dash): debug

* fix(dash): fix error which come when not logged in

* fix(dash)

* fix(dash)

* fix(dash)

* fix(dash)

* feat: add webhook for botlist.space

* style: 🎨 format code

* fix: add authorization verifying

* style: 🎨 format code

* fix(vote): vote on bls also

still not confirmed if webhook triggers

* style: 🎨 format code

* fix(webhooks): minor fixes

* fix(serverinfo): fix bug

ReferenceError: guild is not defined

* fix(dblwebhook): differentiate between support server & bot itself

* style: 🎨 format code

* fix(dblwebhook): ignore test types

* style: 🎨 format code

* debug(dash)

* style: 🎨 format code

* debug(dash/utils)

* debugging

* trying await

* Revert "debugging"

This reverts commit 0a2a422b578268dc302fac7481b5f5a806e299ac.

* fix(dash)

* debugging

* fix(dash/utils)

* fix(dash/utils)

* debug

* fix(dash)

* debug

* style: 🎨 format code

* fix(utils): TypeError: Assignment to constant variable.

* fix(beg): increase chance to get money

* npm(deps): bump discord.js (#175)

Bumps [discord.js](https://github.com/discordjs/discord.js) from 13.0.0-dev.4886ae2.1627257843 to 13.0.0-dev.4886ae2.1627344219.
- [Release notes](https://github.com/discordjs/discord.js/releases)
- [Commits](https://github.com/discordjs/discord.js/commits)

---
updated-dependencies:
- dependency-name: discord.js
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* run install

* fix(beg): remove unwanted code

* fix(dash): fix error guild.iconURL() is not a function

* fix(dash): fix syntax error

* style: 🎨 format code

* Revert "fix(dash): fix syntax error"

This reverts commit 8c20e99d55342ba17f257bee93b9e27a5022888d.

* revert

* fix(dash)

* fix(dashboard.ejs): remove unwanted stuff

* fix: error Unexpected token 'if'

* fix syntax

* fix(ejs code)

* fix bugs

* feat(dash): add basic manage page

* feat(dash): show invite link at times when bot is not invited

* style: 🎨 format code

* fix(include is not a function) & feat(config): add inviteToGuild func

* style: 🎨 format code

* fix: typo

* fix(error)

* fix: ReferenceError: guildId is not defined

* style: 🎨 format code

* fix(dash)

* style: 🎨 format code

* refactor: align image center

* feat(dash): more styles

* fix(dash): sort

* fix(dash): remove card-tools & add max-width & max-height for images

* feat(dash): design profile

* style: 🎨 format code

* build: reinstall

* fix

* fix(syntax)

* debug

* fix(dash/profile)

* minor fix

* build: reinstall djs

* build: reinstall discord-player

* typo

* refactor(dash)

* fix(djs problem): MANAGE_EMOJIS permission was renamed to MANAGE_EMOJIS_AND_STICKERS

* style: 🎨 format code

* fix(dash): minor fixes

* fix(lang cmd): partial fix

After changing the server language you can't switch back to english

* style: 🎨 format code

* refactor(dash): change layout of profile

* fix(dash): seperate wallet

* fix(profile)

* revert

* fix(dash): remove dark-mode

* feat(dash): add prompt=none so that if already authorized, it won't ask now

* Revert "feat(dash): add prompt=none so that if already authorized, it won't ask now"

This reverts commit cce5ab520b72c452cecf72f843bdba934c223a70.

* feat(dash): manage prefix

* style: 🎨 format code

* minor fix

* fix(manage): minor fix

* debug

* style: 🎨 format code

* feat(dash): add breadcrumb for manage route

* fix(manage)

* refactor(dash): move dashboard folder to src folder

* fix(dash)

* workflows: add lint.yml

* build: add eslint-plugin-prettier as devDeps for linting code

* fix(eslint config): add prefer-const: ["error"]

* fix(eslint config): add some new rules also

* fix(eslint config): minor fixes

* refactor: fix problems with eslint :bug:

* fix

* fix

* style: 🎨 format code

* fix

* fix(execute func)

* fix

* fix

* style: 🎨 format code

* feat(vote): check if user has already voted for bls

* style: 🎨 format code

* fix

* style: 🎨 format code

* fix

* feat: add another method to manage language switching

* style: 🎨 format code

* feat(dash): change language from dash too

* style: 🎨 format code

* feat(vote): more clear explanation

* fix(locales/cmds): fix json

* Update .eslintrc.json

* npm(deps): bump mongoose from 5.13.3 to 5.13.4 (#176)

Bumps [mongoose](https://github.com/Automattic/mongoose) from 5.13.3 to 5.13.4.
- [Release notes](https://github.com/Automattic/mongoose/releases)
- [Changelog](https://github.com/Automattic/mongoose/blob/master/History.md)
- [Commits](https://github.com/Automattic/mongoose/compare/5.13.3...5.13.4)

---
updated-dependencies:
- dependency-name: mongoose
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix: small fixes

* style: 🎨 format code

* minor change

* fix(presence)

* fix(dash)

* fix

* fix

* fix(deposit cmd)

* style: 🎨 format code

* fix(lint workflow)

* fix(channel cmd): fix channelIdFromMention not defined

* docs: changelog

* build: bump changelog & version

* npm(deps): bump discord.js (#178)

Bumps [discord.js](https://github.com/discordjs/discord.js) from 13.0.0-dev.4f1f32f.1627517033 to 13.0.0-dev.2675b08.1627603447.
- [Release notes](https://github.com/discordjs/discord.js/releases)
- [Commits](https://github.com/discordjs/discord.js/commits)

---
updated-dependencies:
- dependency-name: discord.js
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* refactor: add customization of welcome & goodbye message in dashboard

changelog for other info

* style: 🎨 format code

* fix: Identifier message has already been declared

* fix(dash)

* fix

* fix

* fix & reply if ... is disabled...

* fix: fix mongoose schema

* fix

* fix(dash): fix when form submitted, some data aren't updated

* fix: logs are sent even when disabled

* fix eslint errors

* build: reinstall

* fix(mod category): fix all commands in mod category

* style: 🎨 format code

* fix(membercount): small fix

* fix(serverinfo): minor fix

* fix: depreciation warning

DeprecationWarning: The message sweeping client options are deprecated, use the makeCache option with a SweptCollection instead.

* style: 🎨 format code

* fix(updateDocs)

* style: 🎨 format code

* fix(deposit): reply if no free space or bank is full

* refactor: use real invite link in invite command

* style: 🎨 format code

* feat(dash): use discord api states, for a secure login

https://discord.com/developers/docs/topics/oauth2#state-and-security

* style: 🎨 format code

* fix bug

* fix

* feat(dash): settings route

* style: 🎨 format code

* fix(dash): debug & small fixes

* style: 🎨 format code

* fix(dash)

* fix(dash): fix error userDB.save() is not a function

* style: 🎨 format code

* debug

* fix(dash): change emoji for goodbye

* fix

* fix(vote): fix api url

* fix(dash) & add limit to bio length

* style: 🎨 format code

* feat(dash): implement csrf

* build: add csurf dep

* fix(dash): fix csrf token error

* fix(release notes): add workflow_dispatch

* feat(vote): switch to buttons for vote cmd

* style: 🎨 format code

* fix(vote)

* style: 🎨 format code

* fix(vote)

* style: 🎨 format code

* refactor: drop support for botlist.space and use discordbotlist.com

* fix(addemoji): fix addemoji command!

* style: 🎨 format code

* fix(vote): ignore dbl temporarily

* fix(testwelcome & testgoodbye): fix bug

* fix(welcome & goodbye logs)

* feat: provide their IDs in message content also

* fix(version): client.botVersion was removed in favour of client.package.version

* fix

* style: 🎨 format code

* Revert "refactor: drop support for botlist.space and use discordbotlist.com"

This reverts commit 460f4bc434a03af4b7db89e08de5d67d25289ab7.

* fix(dash): redirect / to /login

* style: 🎨 format code

* fix(vote)

* fix(vote)

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>