Development (#133)
* Merge branch 'main' into development (#95)

* Merge branch 'development' into main (#90)

* Update Dockerfile

* Create CODEOWNERS

* Update docker-publish.yml

* Update and rename docker-publish.yml to ci.yml

* run npm i

* Update ci.yml

* Update ci.yml

* Update ci.yml

* fix(readme): Break out lines which (#89)

Which are required to be in next line
And minor updates to readme

* npm(deps): bump discord-player (#91)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

* npm(deps): bump discord-player (#96)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Merge branch 'main' into development (#98)

* Dev (#102)

- refactor(version cmd): Use embeds for version cmd
- cmd: New cmd hastbin
- refactor: Use Embed instead of MessageEmbed
- cmds: New cmd tickle
- refactor(uptime cmd): less code, more style
- locales: Add datelaunched to misc.json
- feat: Show more info in suggest command
- fix(Dockerfile): use latest npm version
- locales: Add uptime to misc.json
- deps: Add moment and moment-duration-format
- feat: Show more info in suggest command
- fix(Dockerfile): use latest npm version

* Fix suggest cmd (#104)

* fix(suggest cmd): The links were not shown properly

* chore: 🎨 format code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Fix (#107)

* fix(embed and locale loader): Embed class was not working and load misc in locale loader

* fix: Embed class

* chore: 🎨 format code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* fix: Embed class (#108)

* fix: final fix for Embed class (#109)

* fix: ReferenceError: err is not defined

* fix: emoji in uptime cmd & remove footer (#110)

* fix: emoji in uptime cmd & remove footer

* changelog

* Fix (#111)

* Merge branch 'development' into main (#90)

* Update Dockerfile

* Create CODEOWNERS

* Update docker-publish.yml

* Update and rename docker-publish.yml to ci.yml

* run npm i

* Update ci.yml

* Update ci.yml

* Update ci.yml

* fix(readme): Break out lines which (#89)

Which are required to be in next line
And minor updates to readme

* npm(deps): bump discord-player (#91)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

* npm(deps): bump discord-player (#96)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

* fix(deps): run npm install

* New Crowdin updates (#99)

* New translations categories.json (Romanian)

* New translations categories.json (Dutch)

* New translations categories.json (Portuguese, Brazilian)

* New translations categories.json (Vietnamese)

* New translations categories.json (English)

* New translations categories.json (Chinese Traditional)

* New translations categories.json (Chinese Simplified)

* New translations categories.json (Ukrainian)

* New translations categories.json (Turkish)

* New translations categories.json (Swedish)

* New translations categories.json (Serbian (Cyrillic))

* New translations categories.json (Russian)

* New translations categories.json (Portuguese)

* New translations categories.json (Polish)

* New translations categories.json (Norwegian)

* New translations categories.json (Korean)

* New translations categories.json (French)

* New translations categories.json (Japanese)

* New translations categories.json (Italian)

* New translations categories.json (Hungarian)

* New translations categories.json (Hebrew)

* New translations categories.json (Finnish)

* New translations categories.json (Greek)

* New translations categories.json (German)

* New translations categories.json (Danish)

* New translations categories.json (Czech)

* New translations categories.json (Catalan)

* New translations categories.json (Arabic)

* New translations categories.json (Afrikaans)

* New translations categories.json (Spanish)

* New translations categories.json (Hindi)

* Github Actions(deps): Bump docker/metadata-action from 3.3.0 to 3.4.0 (#101)

Bumps [docker/metadata-action](https://github.com/docker/metadata-action) from 3.3.0 to 3.4.0.
- [Release notes](https://github.com/docker/metadata-action/releases)
- [Commits](https://github.com/docker/metadata-action/compare/98669ae865ea3cffbcbaa878cf57c20bbf1c6c38...f6efe56d565add159ad605568120f5b22712a870)

---
updated-dependencies:
- dependency-name: docker/metadata-action
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Github Actions(deps): Bump docker/build-push-action from 2.5.0 to 2.6.1 (#100)

* Add test (#103)

* deps: Add mocha & mocha-standard

* test: Add tests!!

* chore: 🎨 format code

* deps: Remove mocha-standard

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Fix (#105)

* Merge branch 'main' into development (#95)

* Merge branch 'development' into main (#90)

* Update Dockerfile

* Create CODEOWNERS

* Update docker-publish.yml

* Update and rename docker-publish.yml to ci.yml

* run npm i

* Update ci.yml

* Update ci.yml

* Update ci.yml

* fix(readme): Break out lines which (#89)

Which are required to be in next line
And minor updates to readme

* npm(deps): bump discord-player (#91)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

* npm(deps): bump discord-player (#96)

Bumps [discord-player](https://github.com/Androz2091/discord-player) from 5.0.0-dev.m3 to 5.0.0-dev.29489940b64b555e2e791dcf0662bd2d93a22ef6.
- [Release notes](https://github.com/Androz2091/discord-player/releases)
- [Commits](https://github.com/Androz2091/discord-player/commits)

---
updated-dependencies:
- dependency-name: discord-player
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* fix(deps): run npm install

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Merge branch 'main' into development (#98)

* Dev (#102)

- refactor(version cmd): Use embeds for version cmd
- cmd: New cmd hastbin
- refactor: Use Embed instead of MessageEmbed
- cmds: New cmd tickle
- refactor(uptime cmd): less code, more style
- locales: Add datelaunched to misc.json
- feat: Show more info in suggest command
- fix(Dockerfile): use latest npm version
- locales: Add uptime to misc.json
- deps: Add moment and moment-duration-format
- feat: Show more info in suggest command
- fix(Dockerfile): use latest npm version

* Fix suggest cmd (#104)

* fix(suggest cmd): The links were not shown properly

* chore: 🎨 format code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* fix(embed and locale loader): Embed class was not working and load misc in locale loader

* fix: Embed class

* chore: 🎨 format code

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Revert "Fix (#105)" (#106)

This reverts commit d673216455f9d56fd3b005903db75267552bdca2.

* cmd: New cmd loop

* refactor(music cmds)

* fix(loop cmd): SyntaxError

* chore: 🎨 format code

* fix: await is oy valid under async

* fix: Embed is not defined

* fix: Bot always send that it is rate limited

When error occures in playing music

* fix: Not shwing mode

* docs: commands

* chore: 🎨 format code

* deps: Reinstall to use latest commit

* fix(dockerignore): Ignore unwanted files

* deps: Reinstall deps to fix package-lock.json

* workflows(ci): Tests are added! Add Test in CI

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* docs: Improve contributing guidelines (#112)

* docs: Improve contributing guidelines

* docs(contributing): Add how we use commit names

* Changelog (#113)

* fix(volume cmd): Add usage

* docs: changelog

* fix(contributing guidelines) (#116)

* fix: Channel types are now uppercase (#115)

https://github.com/discordjs/discord.js/pull/6035

* feat: Add customEmojis.json (#118)

* feat: Add src/customEmojis.json

* refactor(botinfo cmd)

* change: Use customEmojis in uptime cmd

* chore: 🎨 format code

* docs: Update contributing guidelines

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* fix: To reduce caching, sweep out messages older than 14 days (#117)

* fix: To reduce caching, sweep out messafes older than 14 days

* docs: changelog

* fix: make an empty commit to run CI workflow again

* New command `listemojis` (#119)

* refactor: Rename src/functions/get.js -> src/helpers/Util.js

* fix: Handle errors while validating function

* fix(help cmd): Log debug as debug not log

* fix: Use servers const instead

* feat: New command listemojis

* chore: 🎨 format code

* docs: changelog

* fix(listemojis cmd)

* chore: 🎨 format code

* deps: reinstall to update lock file

* docs: Add `deps(<title>): <description>` to contributing guidelines

I forgot to add this

* fix(package scripts): looks like mocha won't exit automatically

We have to supply the `--exit` arg

* deps: Add bufferutil for much faster Websocket connection

* run install

* docs: commands

* docs: Add commit names section

- To contributing guidelines

* docs(contributing): Show reference

- From where these lines where took

In a html comment

* fix: Say user about forbidden to play that song

* feat: Add setDebug function & use debugLevel

* fix: SyntaxError

* chore: 🎨 format code

* refactor(setDebug func): return true;

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* New Tests (#120)

* tests: Add new tests

- Commands
    - should be defined in cmds.json
    - should have proper category name

Last time I had made a typo when typing category name for addemoji cmd
Theses tests will avoid those problems

* tests(commands): Fix test 3

Test 3: should have proper category name

Error: TypeError: cmdCats.has is not a function

* chore: 🎨 format code

* build: Add tests category

To release drafter

So that tests are in a separate category in release notes

* fix(workflow): release notes wasn't triggering

For development branch

* fix(config): Release drafter didn't ignore PRs

PRs which had `No-changelog` label wasn't ignored

* fix(config): release drafter

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Fix Dockerfile & Use embeds for eval CMD (#121)

* build: reinstall to update lock

* feat: Use embeds

for eval command

* chore: 🎨 format code

* fix(Dockerfile): Run npm update to install latest versions

Last time to discord-player wan't on the latest version

So Welcome-Bot(beta) failed to play the song

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* build: run npm update

To update lock file

* Github Actions(deps): Bump docker/metadata-action from 3.4.0 to 3.4.1 (#124)

Bumps [docker/metadata-action](https://github.com/docker/metadata-action) from 3.4.0 to 3.4.1.
- [Release notes](https://github.com/docker/metadata-action/releases)
- [Commits](https://github.com/docker/metadata-action/compare/f6efe56d565add159ad605568120f5b22712a870...8b842e721d38d18bea23b57f4c040e53331f4ca2)

---
updated-dependencies:
- dependency-name: docker/metadata-action
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* Github Actions(deps): Bump actions/stale from 3 to 4 (#125)

Bumps [actions/stale](https://github.com/actions/stale) from 3 to 4.
- [Release notes](https://github.com/actions/stale/releases)
- [Changelog](https://github.com/actions/stale/blob/main/CHANGELOG.md)
- [Commits](https://github.com/actions/stale/compare/v3...v4)

---
updated-dependencies:
- dependency-name: actions/stale
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>

* refactor(eval CMD): Add type field to embed

- Move common code to a existing func clean

* fix: status func is depreciated

So switch to sendStatus

* Refactor(cmds) (#127)

* tests(Commands): Add new test

- should have only lowercase names and aliases

* feat: Add optionHandler

- This option handler, lets you to make an option required or optional
- Returns 2 functions in an object: required & optional

* docs: changelog & build: use shard.js for npm start script

- actually I shoudn't change the script, but for testing, lets start now itself

* feat: Add new cmd: `shards`

- Shows info about bot's shards

* chore: 🎨 format code

* fix(tests): Fix 1 minor typo

Change oy to only

* fix(function): createOptionHandler had a minor bug which is fixed now!

* deps: Add ascii-table

Will be used by shards command

* fix(function): skip array merging in createOptionHandler

* refactor(cmds): Change the whole structure of commands

- Also removes stopTyping and uses sendTyping instead of startTyping
https://github.com/discordjs/discord.js/pull/6114

* fix(cmds): Fix SyntaxError & docs: commands

* chore: 🎨 format code

* fix: Small permissions related issue

* chore: 🎨 format code

* fix(cmds): Sometimes, I forget to remove usage in cmds when I copy paste

Removed in this commit

* fix(cmd): Remove an unwanted log I added in help cmd to debug

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* build: reinstall to update lockfile

* fix(avatar cmd): It wasn't accepting user ids

* fix: error in avatar cmd

* refactor(log embeds): Improve style, color in bot-logs for embeds

Also add shardId

* fix: webserver.js should start from shard.js

* run install

* Testing (#131)

* fix(help cmd): help for perms in pecific cmds were not shown

* chore: 🎨 format code

* updated lock file version

* Delete package-lock.json

* Create package-lock.json

* build: fix djs version in package.json

* Update package.json

Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: ABHISHEK Joshi <abhijoshi2k@gmail.com>