New Tests (#120)
* tests: Add new tests

- Commands
    - should be defined in cmds.json
    - should have proper category name

Last time I had made a typo when typing category name for addemoji cmd
Theses tests will avoid those problems

* tests(commands): Fix test 3

Test 3: should have proper category name

Error: TypeError: cmdCats.has is not a function

* chore: 🎨 format code

* build: Add tests category

To release drafter

So that tests are in a separate category in release notes

* fix(workflow): release notes wasn't triggering

For development branch

* fix(config): Release drafter didn't ignore PRs

PRs which had `No-changelog` label wasn't ignored

* fix(config): release drafter

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>