feat: Add economy commands (#149)
* feat: Add user model/schema

With functions
- addUser.js
- getUser.js
- removeUser.js
- updateUser.js

* feat: add user to db when prerunning if not yet added

* feat: New cmd `daily` and new category `Economy`

Note: There's a bug in displaying time left

* chore: 🎨 format code

* build: Add deps: moment-countdown, countdown

* fix(daily cmd): The time left was displaying wrong time

* Revert "build: Add deps: moment-countdown, countdown"

This reverts commit 3fd5ec26b53f603f0df6673992a72250a2ebc4f8.

* chore: 🎨 format code

* docs: changelog

* docs: commands

* feat: New cmd `balance`

* style: 🎨 format code

* fix(balance cmd): Fix percentage

* style: 🎨 format code

* fix(balance cmd)

* style: 🎨 format code

* fix(balance): Fix, all requests would return your balance

And also handle no Welcome-Bot account for that user

* fix(balance)

* fix(balance)

* fix(balance)

* feat: New cmd `deposit`

* style: 🎨 format code

* feat: New cmd `give`

* style: 🎨 format code

* docs: changelog

* feat: Add registeredAt to User schema

* Fix daily.js

* fix(daily): Use moment again :-)

Reasons I need moment
- Language support: It would change a minute (in en) to une minute (in fr)
- 100+ languages support

* fix(economy): Change emoji

* fix(daily cmd)

* feat: New cmd `beg`

* style: 🎨 format code

* feat: New cmd `withdraw`

* feat: New cmd `profile` & fix(beg): Remove unwanted logs

* style: 🎨 format code

* fix(beg): Randomize chance

* style: 🎨 format code

* fix(beg): Increase cooldown & fix Infinity problem

* docs: commands

* feat: New cmd `setbio`

* style: 🎨 format code

* feat(profile): Display user bio

* fix(locales/misc): Add bio

* fix(profile)

* feat(userSchema): Add logged

Shows if user has ever logged in to the dashboard

* style: 🎨 format code

* feat(economy): Increase amount & fix setbio cmd

* fix(locales/cmds): Fix typo

* feat: New cmd `rob`

* feat(locales/cmds): Add translations for rob cmd

* style: 🎨 format code

* build: bump changelog

* docs: changelog

* build: reinstall discord.js

* fix(withdraw): Add alias with for withdraw cmd

* feat: We now have 60+ commands

* feat(rob cmd): Should have failure also!

* style: 🎨 format code

* docs: commands

* fix(rob cmd): Remove cooldown if invalid user

* fix(rob cmd): Fix error

Assignment to constant...

* fix(rob)

* fix typo

* fix(tests): Should exit with a process code

* Revert last commit (not full)

* ci: run on prs to v2 br also & fix(testwelcome cmd)

fix(testwelcome cmd): rename src/commands/general/test.js -> src/commands/testwelcome.js

* fix(avatar cmd)

We were getting error when running tests
Error: Some of them have duplicate names or aliases, they are: profile

* fix(rob cmd): remove cooldown in some cases

* feat(rob): Give user some chance to win also properly

* style: 🎨 format code

* fix(rob): More chance for success

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: ABHISHEK Joshi <abhijoshi2k@gmail.com>